"""P53 — Wave 23 Neural Cellular Automata terrain refinement smoke.

Validates the :mod:`engine.neural_terrain` post-pass against a chunk
generated by the legacy or anchored pipeline.

  1. Public API surface present.
  2. Pure-function determinism : two runs on the same chunk produce
     bit-identical results.
  3. Refinement actually modifies the chunk (mean delta > 0, std rises
     or falls in a controlled way).
  4. Energy conservation : total elevation drift stays within < 10 %
     of original (no runaway).
  5. Boundary respected : land cells stay land, abyss stays abyss.
  6. ``install_neural_terrain`` is idempotent.
  7. Streamer wrap : a fresh ``streamer.get`` on cache-miss triggers
     refinement and increments ``chunks_refined``.
  8. ``apply_to_existing_chunks`` retro-refines cached chunks.
  9. ``uninstall_neural_terrain`` restores the original streamer.
"""
from __future__ import annotations

import io
import os
import sys
import traceback

if hasattr(sys.stdout, "buffer"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8",
                                  errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8",
                                  errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, ROOT)

import numpy as np                                                      # noqa: E402

from engine.sim import Simulation, SimConfig                            # noqa: E402
from engine.world import generate_chunk, TerrainParams, Biome           # noqa: E402
from engine.neural_terrain import (                                     # noqa: E402
    NeuralTerrainConfig, NeuralTerrainState,
    refine_chunk_elevation, install_neural_terrain,
    uninstall_neural_terrain, apply_to_existing_chunks,
    neural_terrain_state,
)


def _row(label, ok, detail=""):
    return f"  [{'OK  ' if ok else 'FAIL'}] {label:62s} {detail}"


def _build_sim(name: str, seed: int = 0xCAFEBABE_42):
    cfg = SimConfig(
        name=name, seed=seed & 0xFFFFFFFFFFFFFFFF,
        founders=2, max_agents=4,
        bounds_km=(0.5, 0.5), spawn_radius_m=50.0,
        drive_accel=1500.0, cultures=1,
    )
    return Simulation(cfg)


def main() -> int:
    print("=" * 78)
    print("P53 — Wave 23 NCA terrain refinement smoke")
    print("=" * 78)
    failures = 0

    # Step 1 — API surface.
    ok = all(name in globals() for name in (
        "NeuralTerrainConfig", "NeuralTerrainState",
        "refine_chunk_elevation", "install_neural_terrain",
        "uninstall_neural_terrain", "apply_to_existing_chunks",
        "neural_terrain_state"))
    print(_row("step 1 - public API exposed", ok, ""))
    if not ok:
        failures += 1

    # Build a base chunk via the legacy pipeline. FBM at (0,0,0) often
    # lands at sea level; we scan a few coords for one with > 30 % land
    # cells so the NCA has substrate to refine.
    seed = 0xCAFEBABE_42 & 0xFFFFFFFFFFFFFFFF
    params = TerrainParams()
    land_coord = None
    for tc in [(0, 0, 0), (10, 10, 0), (50, 50, 0), (100, 100, 0),
                (-50, 50, 0), (200, 0, 0), (0, 200, 0)]:
        probe = generate_chunk(seed, tc, params)
        if (probe.height > 0.0).mean() > 0.3:
            land_coord = tc
            break
    assert land_coord is not None, "no land coord found for test"
    chunk_a = generate_chunk(seed, land_coord, params)
    chunk_b = generate_chunk(seed, land_coord, params)
    H_orig = chunk_a.height.copy()
    H_orig_b = chunk_b.height.copy()
    assert np.array_equal(H_orig, H_orig_b), "base chunks must match"
    print(f"        test coord={land_coord} land_frac="
          f"{float((H_orig > 0).mean()):.2f}")

    # Step 2 — determinism on the pure-function overlay.
    cfg = NeuralTerrainConfig(iterations=4)
    refine_chunk_elevation(chunk_a, cfg)
    refine_chunk_elevation(chunk_b, cfg)
    ok = np.array_equal(chunk_a.height, chunk_b.height)
    print(_row("step 2 - determinism on pure-function overlay",
               ok, f"max_diff={float(np.abs(chunk_a.height - chunk_b.height).max()):.6f}"))
    if not ok:
        failures += 1

    # Step 3 — refinement changes the field non-trivially.
    delta = chunk_a.height - H_orig
    mean_abs_delta = float(np.abs(delta).mean())
    max_abs_delta = float(np.abs(delta).max())
    ok = mean_abs_delta > 0.01 and max_abs_delta > 0.1
    print(_row("step 3 - refinement produces a measurable delta",
               ok, f"mean|dH|={mean_abs_delta:.3f}m max|dH|={max_abs_delta:.3f}m"))
    if not ok:
        failures += 1

    # Step 4 — energy conservation : mean elevation drift < 10 %.
    mean_orig = float(H_orig.mean())
    mean_after = float(chunk_a.height.mean())
    drift = abs(mean_after - mean_orig)
    rel = drift / (abs(mean_orig) + 1.0)
    ok = rel < 0.10
    print(_row("step 4 - mean elevation drift bounded",
               ok, f"drift={drift:.2f}m rel={rel * 100:.2f}%"))
    if not ok:
        failures += 1

    # Step 5 — land cells stay land, abyss stays abyss.
    # (Apply NCA to a chunk that has both land and ocean.)
    chunk_mix = generate_chunk(seed ^ 0xFF, (5, 7, 0), params)
    H_mix_orig = chunk_mix.height.copy()
    refine_chunk_elevation(chunk_mix, cfg)
    abyssal_before = H_mix_orig < -50.0
    abyssal_after = chunk_mix.height < -50.0
    # Frozen abyssal mask : where it WAS deep, it stays deep.
    abyssal_consistent = np.array_equal(H_mix_orig[abyssal_before],
                                          chunk_mix.height[abyssal_before])
    ok = abyssal_consistent
    print(_row("step 5 - abyssal cells frozen by NCA",
               ok, f"abyssal_before={int(abyssal_before.sum())} "
                   f"after={int(abyssal_after.sum())}"))
    if not ok:
        failures += 1

    # Step 6 — install idempotent.
    sim = _build_sim("p53_nca")
    sim.step()
    state1 = install_neural_terrain(sim, cfg)
    state2 = install_neural_terrain(sim, cfg)
    ok = state1 is state2
    print(_row("step 6 - install idempotent (same state)", ok, ""))
    if not ok:
        failures += 1

    # Step 7 — streamer wrap refines on cache miss. We feed it the
    # land_coord we already validated has > 30 % land.
    sim.streamer.clear_cache()  # ensure cache miss
    state1.decisions.clear()
    n_before = state1.chunks_refined
    state1.chunks_refined = 0
    state1.total_iterations = 0
    ch_new = sim.streamer.get(0, land_coord)
    n_after = state1.chunks_refined
    ok = (ch_new is not None and n_after == 1
          and state1.total_iterations >= cfg.iterations)
    print(_row("step 7 - streamer wrap refines on cache miss",
               ok, f"chunks_refined={n_after} "
                   f"iters_total={state1.total_iterations} "
                   f"(land_coord={land_coord})"))
    if not ok:
        failures += 1

    # Step 8 — apply_to_existing_chunks retro-refines.
    sim2 = _build_sim("p53_retro")
    for _ in range(2):
        sim2.step()
    n_cached = len(sim2.streamer.cache)
    state_retro = install_neural_terrain(sim2, cfg)
    n_new = apply_to_existing_chunks(sim2)
    ok = (n_new == n_cached
          and state_retro.chunks_refined == n_cached)
    print(_row("step 8 - apply_to_existing_chunks retro-refines all",
               ok, f"n_cached={n_cached} n_new={n_new}"))
    if not ok:
        failures += 1

    # Step 9 — uninstall restores streamer.
    streamer = sim.streamer
    ok1 = uninstall_neural_terrain(sim)
    ok2 = (getattr(streamer, "_neural_terrain_orig_get", None) is None
           and getattr(sim, "_neural_terrain_state", None) is None)
    # Confirm fresh get still works.
    sim.streamer.clear_cache()
    ch_post = sim.streamer.get(0, (20, 20, 0))
    ok3 = ch_post is not None
    ok = ok1 and ok2 and ok3
    print(_row("step 9 - uninstall cleanly detaches",
               ok, f"uninst={ok1} hook_clear={ok2} fresh_ok={ok3}"))
    if not ok:
        failures += 1

    print(f"\nNeural terrain state on sim2: {neural_terrain_state(sim2)}")

    total = 9
    passed = total - failures
    print("=" * 78)
    if failures == 0:
        print(f"RESULT: {total}/{total} PASS")
        return 0
    else:
        print(f"RESULT: {passed}/{total} PASS, {failures} FAIL")
        return 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        traceback.print_exc()
        sys.exit(2)
